import type { ThreadsCategory } from "./types";

/**
 * Buying-intent taxonomy for Threads lead monitoring.
 * Edit the keyword lists here to tune what the monitor hunts.
 * Every keyword is also matched against the INTENT_TRIGGERS list below.
 */
export const THREADS_CATEGORIES: ThreadsCategory[] = [
  {
    id: "web-design",
    label: "Web Design",
    fiverrTag: "Web Development",
    keywords: [
      "website design",
      "need a website",
      "build my website",
      "my own website",
      "portfolio website",
      "website designer",
      "web designer",
      "web developer",
      "website developer",
      "website development",
      "redesign my website",
      "website redesign",
      "make me a website",
      "create a website",
      "build a website",
      "site for my",
      "personal website",
      "business website",
      "website for my business",
      "website for my",
      "build me a website",
      "need a site",
      "upgrade my website",
      "fix my website",
      "website overhaul",
      "new website",
      "website for my company",
    ],
  },
  {
    id: "landing-page",
    label: "Landing Pages",
    fiverrTag: "Landing Page Design",
    keywords: [
      "landing page",
      "high-converting landing page",
      "waitlist page",
      "coming soon page",
      "squeeze page",
      "sales page",
      "product page design",
      "pricing page",
      "hero section",
      "convert my traffic",
      "conversion rate",
    ],
  },
  {
    id: "saas-app",
    label: "SaaS & Apps",
    fiverrTag: "App Development",
    keywords: [
      "building a saas",
      "my saas",
      "saas launch",
      "launch my saas",
      "need an mvp",
      "mvp builder",
      "app developer",
      "mobile app",
      "ios app",
      "android app",
      "web app",
      "no-code app",
      "saas landing",
      "product launch",
      "developers for",
      "tech co-founder",
      "build an app",
      "build a saas",
      "saas app",
      "want a saas",
      "app for my business",
      "saas for my",
      "mvp for my",
      "software for my business",
      "custom software",
      "web app for my",
      "app for my company",
      "software development",
    ],
  },
  {
    id: "branding",
    label: "Branding & Logo",
    fiverrTag: "Branding",
    keywords: [
      "logo design",
      "logo for",
      "logo creator",
      "logo designer",
      "design a logo",
      "brand identity",
      "branding package",
      "rebrand",
      "rebranding",
      "brand guidelines",
      "design my logo",
      "new logo",
      "brand designer",
      "brand for my",
      "visual identity",
    ],
  },
  {
    id: "social-media",
    label: "Social Media & Marketing",
    fiverrTag: "Social Media Marketing",
    keywords: [
      "social media manager",
      "marketing agency",
      "ads manager",
      "run my ads",
      "meta ads",
      "facebook ads",
      "tiktok ads",
      "email marketing",
      "seo for",
      "content strategy",
      "marketing strategy",
      "marketing for my",
    ],
  },
  {
    id: "copywriting",
    label: "Copywriting & Content",
    fiverrTag: "Copywriting",
    keywords: [
      "copywriter",
      "sales copy",
      "email sequence",
      "website copy",
      "landing page copy",
      "content writer",
      "script writer",
      "video script",
      "write my",
      "rewrite my",
      "copy for",
    ],
  },
  {
    id: "video",
    label: "Video & Editing",
    fiverrTag: "Video Editing",
    keywords: [
      "video editor",
      "video editing",
      "edit my videos",
      "edit my video",
      "youtube editor",
      "youtube editing",
      "edit videos for",
      "editing for my",
      "looking for an editor",
      "need an editor",
      "find an editor",
      "hiring a video editor",
      "podcast editor",
      "podcast editing",
      "long form editor",
      "video editing for my",
      "video editor for my",
      "commercial editing",
      "motion graphics",
      "thumbnail designer",
      "youtube thumbnail",
      "video production",
    ],
  },
  {
    id: "ai-automation",
    label: "AI & Automation",
    fiverrTag: "AI / No-Code Automation",
    keywords: [
      "ai automation",
      "ai agent",
      "chatbot",
      "make.com",
      "zapier",
      "n8n",
      "automate my business",
      "automate my workflow",
      "ai tools for",
      "gpt for",
      "ai developer",
      "automation agency",
    ],
  },
  {
    id: "ecommerce",
    label: "E-commerce",
    fiverrTag: "E-commerce Development",
    keywords: [
      "shopify store",
      "dropshipping store",
      "dropshipping site",
      "ecommerce site",
      "product pages",
      "my store",
      "shopify",
      "woocommerce",
      "online store",
      "store design",
    ],
  },
  {
    id: "systems",
    label: "Systems & Ops",
    fiverrTag: "Operations / Systems",
    keywords: [
      "notion setup",
      "notion for",
      "airtable",
      "crm setup",
      "crm for",
      "standard operating procedure",
      "sop",
      "business systems",
      "operations manager",
      "workflow",
      "onboarding process",
    ],
  },
];

/**
 * Job-role/service posts we never want as leads (they're hiring PA/VA/data
 * staff, not buying design services). Posts matching any term are skipped
 * and marked seen so they never come back.
 */
export const EXCLUDED_TERMS = [
  "personal assistant",
  "virtual assistant",
  "data entry",
  "document typing",
  "administrative assistant",
  "admin assistant",
  "customer support role",
  "customer service rep",
  "call center",
  "transcription",
  "bookkeeping",
  "accounting assistant",
  "telemarketing",
  "chat support",
  "back office",
  "office assistant",
  "secretary",
  "typist",
  "proofreading job",
  "hiring a pa",
  "hire a pa",
  "pa needed",
  "pa required",
  "looking for a pa",
  "virtual admin",
];

export function isExcludedPost(text: string): boolean {
  const t = text.toLowerCase();
  return EXCLUDED_TERMS.some((term) => t.includes(term));
}

export const INTENT_TRIGGERS = [
  "looking for",
  "need help",
  "need a",
  "need someone",
  "who can",
  "anyone know",
  "anyone recommend",
  "recommend",
  "hiring",
  "hiring a",
  "launching",
  "launching soon",
  "starting my",
  "starting a",
  "side hustle",
  "building my",
  "just launched",
  "launched my",
  "my budget",
  "how much would",
  "how much does",
  "advice",
  "help me",
  "help me build",
  "help me find",
  "i want to build",
  "i want to start",
  "i want to create",
  "i'm looking",
  "im looking",
  "can someone",
  "dming",
  "dm me",
  "message me",
  "willing to pay",
  "pay someone",
  "freelancer",
  "agency",
  "quote me",
  "price",
  "cost",
  "suggestions",
  "ideas for",
  "what should i use",
  "what tool",
  "best way to",
];

/**
 * Cheap pre-filter: post must mention an intent trigger. Category keywords
 * give the LLM a head start, but posts from keyword-targeted surfaces (tag
 * pages) with clear intent but no exact keyword still pass as "other" — the
 * LLM scoring is the real judge.
 */
export function hasBuyingIntent(text: string): string | null {
  const t = text.toLowerCase();
  if (t.length > 600) return null;
  if (!INTENT_TRIGGERS.some((trigger) => t.includes(trigger))) return null;
  for (const cat of THREADS_CATEGORIES) {
    if (cat.keywords.some((kw) => t.includes(kw))) return cat.id;
  }
  return "other";
}
