import type { ThreadsCategory } from "./types";

/**
 * Buying-intent taxonomy for Threads lead monitoring.
 * Edit the keyword lists here to tune what the monitor hunts.
 * Every keyword is also matched against the INTENT_TRIGGERS list below.
 */
export const THREADS_CATEGORIES: ThreadsCategory[] = [
  {
    id: "web-design",
    label: "Web Design",
    fiverrTag: "Web Development",
    keywords: [
      "website design",
      "need a website",
      "build my website",
      "my own website",
      "portfolio website",
      "website designer",
      "web designer",
      "web developer",
      "redesign my website",
      "website redesign",
      "make me a website",
      "create a website",
      "site for my",
      "personal website",
      "business website",
    ],
  },
  {
    id: "landing-page",
    label: "Landing Pages",
    fiverrTag: "Landing Page Design",
    keywords: [
      "landing page",
      "high-converting landing page",
      "waitlist page",
      "coming soon page",
      "squeeze page",
      "sales page",
      "product page design",
      "pricing page",
      "hero section",
      "convert my traffic",
      "conversion rate",
    ],
  },
  {
    id: "saas-app",
    label: "SaaS & Apps",
    fiverrTag: "App Development",
    keywords: [
      "building a saas",
      "my saas",
      "saas launch",
      "launch my saas",
      "need an mvp",
      "mvp builder",
      "app developer",
      "mobile app",
      "ios app",
      "android app",
      "web app",
      "no-code app",
      "saas landing",
      "product launch",
      "developers for",
      "tech co-founder",
      "build an app",
    ],
  },
  {
    id: "branding",
    label: "Branding & Logo",
    fiverrTag: "Branding",
    keywords: [
      "logo design",
      "logo for",
      "brand identity",
      "branding package",
      "rebrand",
      "rebranding",
      "brand guidelines",
      "design my logo",
      "new logo",
      "brand designer",
      "visual identity",
    ],
  },
  {
    id: "social-media",
    label: "Social Media & Marketing",
    fiverrTag: "Social Media Marketing",
    keywords: [
      "social media manager",
      "grow my page",
      "grow my account",
      "marketing agency",
      "ads manager",
      "run my ads",
      "meta ads",
      "facebook ads",
      "tiktok ads",
      "email marketing",
      "seo for",
      "content strategy",
      "marketing strategy",
      "marketing for my",
    ],
  },
  {
    id: "copywriting",
    label: "Copywriting & Content",
    fiverrTag: "Copywriting",
    keywords: [
      "copywriter",
      "sales copy",
      "email sequence",
      "website copy",
      "landing page copy",
      "content writer",
      "script writer",
      "video script",
      "write my",
      "rewrite my",
      "copy for",
    ],
  },
  {
    id: "video",
    label: "Video & Editing",
    fiverrTag: "Video Editing",
    keywords: [
      "video editor",
      "short form editor",
      "youtube editor",
      "motion graphics",
      "edit my videos",
      "video editing",
      "thumbnail designer",
      "youtube thumbnail",
      "faceless channel",
      "faceless videos",
    ],
  },
  {
    id: "ai-automation",
    label: "AI & Automation",
    fiverrTag: "AI / No-Code Automation",
    keywords: [
      "ai automation",
      "ai agent",
      "chatbot",
      "make.com",
      "zapier",
      "n8n",
      "automate my business",
      "automate my workflow",
      "ai tools for",
      "gpt for",
      "ai developer",
      "automation agency",
    ],
  },
  {
    id: "ecommerce",
    label: "E-commerce",
    fiverrTag: "E-commerce Development",
    keywords: [
      "shopify store",
      "dropshipping store",
      "dropshipping site",
      "ecommerce site",
      "product pages",
      "my store",
      "shopify",
      "woocommerce",
      "online store",
      "store design",
    ],
  },
  {
    id: "systems",
    label: "Systems & Ops",
    fiverrTag: "Operations / Systems",
    keywords: [
      "notion setup",
      "notion for",
      "airtable",
      "crm setup",
      "crm for",
      "standard operating procedure",
      "sop",
      "business systems",
      "operations manager",
      "workflow",
      "onboarding process",
    ],
  },
];

export const INTENT_TRIGGERS = [
  "looking for",
  "need help",
  "need a",
  "need someone",
  "who can",
  "anyone know",
  "anyone recommend",
  "recommend",
  "hiring",
  "hiring a",
  "launching",
  "launching soon",
  "starting my",
  "starting a",
  "side hustle",
  "building my",
  "just launched",
  "launched my",
  "my budget",
  "how much would",
  "how much does",
  "advice",
  "help me",
  "help me build",
  "help me find",
  "i want to build",
  "i want to start",
  "i want to create",
  "i'm looking",
  "im looking",
  "can someone",
  "dming",
  "dm me",
  "message me",
  "willing to pay",
  "pay someone",
  "freelancer",
  "agency",
  "quote me",
  "price",
  "cost",
  "suggestions",
  "ideas for",
  "what should i use",
  "what tool",
  "best way to",
];

/** Cheap pre-filter: post must mention a category keyword AND an intent trigger. */
export function hasBuyingIntent(text: string): string | null {
  const t = text.toLowerCase();
  if (t.length > 600) return null;
  if (!INTENT_TRIGGERS.some((trigger) => t.includes(trigger))) return null;
  for (const cat of THREADS_CATEGORIES) {
    if (cat.keywords.some((kw) => t.includes(kw))) return cat.id;
  }
  return null;
}
