/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThumbnailTestRouteImport } from './routes/thumbnail-test'
import { Route as ThreadsQueueRouteImport } from './routes/threads-queue'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ShadowbanDetectorRouteImport } from './routes/shadowban-detector'
import { Route as SelectPlanRouteImport } from './routes/select-plan'
import { Route as RetrainThumbnailRouteImport } from './routes/retrain-thumbnail'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PreAnalysisRouteImport } from './routes/pre-analysis'
import { Route as PartnerProgramRouteImport } from './routes/partner-program'
import { Route as NicheRankerRouteImport } from './routes/niche-ranker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DestroyRouteImport } from './routes/destroy'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ClearRouteImport } from './routes/clear'
import { Route as BlueprintRouteImport } from './routes/blueprint'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RefSlugRouteImport } from './routes/ref.$slug'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as PartnerDashboardRouteImport } from './routes/partner/dashboard'
import { Route as BlogThumbnailsMatterRouteImport } from './routes/blog.thumbnails-matter'
import { Route as BlogNicheFindingGuideRouteImport } from './routes/blog.niche-finding-guide'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiCommissionsRouteImport } from './routes/api/commissions'
import { Route as AdminPayoutsRouteImport } from './routes/admin/payouts'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as ApiTrainingRetrainThumbnailRouteImport } from './routes/api/training/retrain-thumbnail'
import { Route as ApiThreadsExportRouteImport } from './routes/api/threads/export'
import { Route as ApiThreadsAuthRouteImport } from './routes/api/threads/auth'
import { Route as ApiLemonPortalRouteImport } from './routes/api/lemon/portal'
import { Route as ApiLemonCheckoutRouteImport } from './routes/api/lemon/checkout'

const ThumbnailTestRoute = ThumbnailTestRouteImport.update({
  id: '/thumbnail-test',
  path: '/thumbnail-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsQueueRoute = ThreadsQueueRouteImport.update({
  id: '/threads-queue',
  path: '/threads-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowbanDetectorRoute = ShadowbanDetectorRouteImport.update({
  id: '/shadowban-detector',
  path: '/shadowban-detector',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectPlanRoute = SelectPlanRouteImport.update({
  id: '/select-plan',
  path: '/select-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrainThumbnailRoute = RetrainThumbnailRouteImport.update({
  id: '/retrain-thumbnail',
  path: '/retrain-thumbnail',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreAnalysisRoute = PreAnalysisRouteImport.update({
  id: '/pre-analysis',
  path: '/pre-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerProgramRoute = PartnerProgramRouteImport.update({
  id: '/partner-program',
  path: '/partner-program',
  getParentRoute: () => rootRouteImport,
} as any)
const NicheRankerRoute = NicheRankerRouteImport.update({
  id: '/niche-ranker',
  path: '/niche-ranker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DestroyRoute = DestroyRouteImport.update({
  id: '/destroy',
  path: '/destroy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ClearRoute = ClearRouteImport.update({
  id: '/clear',
  path: '/clear',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintRoute = BlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RefSlugRoute = RefSlugRouteImport.update({
  id: '/ref/$slug',
  path: '/ref/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDashboardRoute = PartnerDashboardRouteImport.update({
  id: '/partner/dashboard',
  path: '/partner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogThumbnailsMatterRoute = BlogThumbnailsMatterRouteImport.update({
  id: '/thumbnails-matter',
  path: '/thumbnails-matter',
  getParentRoute: () => BlogRoute,
} as any)
const BlogNicheFindingGuideRoute = BlogNicheFindingGuideRouteImport.update({
  id: '/niche-finding-guide',
  path: '/niche-finding-guide',
  getParentRoute: () => BlogRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommissionsRoute = ApiCommissionsRouteImport.update({
  id: '/api/commissions',
  path: '/api/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const ApiTrainingRetrainThumbnailRoute =
  ApiTrainingRetrainThumbnailRouteImport.update({
    id: '/api/training/retrain-thumbnail',
    path: '/api/training/retrain-thumbnail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiThreadsExportRoute = ApiThreadsExportRouteImport.update({
  id: '/api/threads/export',
  path: '/api/threads/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThreadsAuthRoute = ApiThreadsAuthRouteImport.update({
  id: '/api/threads/auth',
  path: '/api/threads/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLemonPortalRoute = ApiLemonPortalRouteImport.update({
  id: '/api/lemon/portal',
  path: '/api/lemon/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLemonCheckoutRoute = ApiLemonCheckoutRouteImport.update({
  id: '/api/lemon/checkout',
  path: '/api/lemon/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/billing': typeof BillingRoute
  '/blog': typeof BlogRouteWithChildren
  '/blueprint': typeof BlueprintRoute
  '/clear': typeof ClearRoute
  '/cookies': typeof CookiesRoute
  '/destroy': typeof DestroyRoute
  '/faq': typeof FaqRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/niche-ranker': typeof NicheRankerRoute
  '/partner-program': typeof PartnerProgramRoute
  '/pre-analysis': typeof PreAnalysisRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/retrain-thumbnail': typeof RetrainThumbnailRoute
  '/select-plan': typeof SelectPlanRoute
  '/shadowban-detector': typeof ShadowbanDetectorRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/threads-queue': typeof ThreadsQueueRoute
  '/thumbnail-test': typeof ThumbnailTestRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/api/commissions': typeof ApiCommissionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/niche-finding-guide': typeof BlogNicheFindingGuideRoute
  '/blog/thumbnails-matter': typeof BlogThumbnailsMatterRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/ref/$slug': typeof RefSlugRoute
  '/api/lemon/checkout': typeof ApiLemonCheckoutRoute
  '/api/lemon/portal': typeof ApiLemonPortalRoute
  '/api/threads/auth': typeof ApiThreadsAuthRoute
  '/api/threads/export': typeof ApiThreadsExportRoute
  '/api/training/retrain-thumbnail': typeof ApiTrainingRetrainThumbnailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/billing': typeof BillingRoute
  '/blog': typeof BlogRouteWithChildren
  '/blueprint': typeof BlueprintRoute
  '/clear': typeof ClearRoute
  '/cookies': typeof CookiesRoute
  '/destroy': typeof DestroyRoute
  '/faq': typeof FaqRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/niche-ranker': typeof NicheRankerRoute
  '/partner-program': typeof PartnerProgramRoute
  '/pre-analysis': typeof PreAnalysisRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/retrain-thumbnail': typeof RetrainThumbnailRoute
  '/select-plan': typeof SelectPlanRoute
  '/shadowban-detector': typeof ShadowbanDetectorRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/threads-queue': typeof ThreadsQueueRoute
  '/thumbnail-test': typeof ThumbnailTestRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/api/commissions': typeof ApiCommissionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/niche-finding-guide': typeof BlogNicheFindingGuideRoute
  '/blog/thumbnails-matter': typeof BlogThumbnailsMatterRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/ref/$slug': typeof RefSlugRoute
  '/api/lemon/checkout': typeof ApiLemonCheckoutRoute
  '/api/lemon/portal': typeof ApiLemonPortalRoute
  '/api/threads/auth': typeof ApiThreadsAuthRoute
  '/api/threads/export': typeof ApiThreadsExportRoute
  '/api/training/retrain-thumbnail': typeof ApiTrainingRetrainThumbnailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/billing': typeof BillingRoute
  '/blog': typeof BlogRouteWithChildren
  '/blueprint': typeof BlueprintRoute
  '/clear': typeof ClearRoute
  '/cookies': typeof CookiesRoute
  '/destroy': typeof DestroyRoute
  '/faq': typeof FaqRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/niche-ranker': typeof NicheRankerRoute
  '/partner-program': typeof PartnerProgramRoute
  '/pre-analysis': typeof PreAnalysisRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/retrain-thumbnail': typeof RetrainThumbnailRoute
  '/select-plan': typeof SelectPlanRoute
  '/shadowban-detector': typeof ShadowbanDetectorRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/threads-queue': typeof ThreadsQueueRoute
  '/thumbnail-test': typeof ThumbnailTestRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/api/commissions': typeof ApiCommissionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/niche-finding-guide': typeof BlogNicheFindingGuideRoute
  '/blog/thumbnails-matter': typeof BlogThumbnailsMatterRoute
  '/partner/dashboard': typeof PartnerDashboardRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/ref/$slug': typeof RefSlugRoute
  '/api/lemon/checkout': typeof ApiLemonCheckoutRoute
  '/api/lemon/portal': typeof ApiLemonPortalRoute
  '/api/threads/auth': typeof ApiThreadsAuthRoute
  '/api/threads/export': typeof ApiThreadsExportRoute
  '/api/training/retrain-thumbnail': typeof ApiTrainingRetrainThumbnailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/billing'
    | '/blog'
    | '/blueprint'
    | '/clear'
    | '/cookies'
    | '/destroy'
    | '/faq'
    | '/history'
    | '/login'
    | '/niche-ranker'
    | '/partner-program'
    | '/pre-analysis'
    | '/privacy-policy'
    | '/retrain-thumbnail'
    | '/select-plan'
    | '/shadowban-detector'
    | '/support'
    | '/terms'
    | '/threads-queue'
    | '/thumbnail-test'
    | '/admin/dashboard'
    | '/admin/payouts'
    | '/api/commissions'
    | '/auth/callback'
    | '/blog/niche-finding-guide'
    | '/blog/thumbnails-matter'
    | '/partner/dashboard'
    | '/payment/success'
    | '/ref/$slug'
    | '/api/lemon/checkout'
    | '/api/lemon/portal'
    | '/api/threads/auth'
    | '/api/threads/export'
    | '/api/training/retrain-thumbnail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/billing'
    | '/blog'
    | '/blueprint'
    | '/clear'
    | '/cookies'
    | '/destroy'
    | '/faq'
    | '/history'
    | '/login'
    | '/niche-ranker'
    | '/partner-program'
    | '/pre-analysis'
    | '/privacy-policy'
    | '/retrain-thumbnail'
    | '/select-plan'
    | '/shadowban-detector'
    | '/support'
    | '/terms'
    | '/threads-queue'
    | '/thumbnail-test'
    | '/admin/dashboard'
    | '/admin/payouts'
    | '/api/commissions'
    | '/auth/callback'
    | '/blog/niche-finding-guide'
    | '/blog/thumbnails-matter'
    | '/partner/dashboard'
    | '/payment/success'
    | '/ref/$slug'
    | '/api/lemon/checkout'
    | '/api/lemon/portal'
    | '/api/threads/auth'
    | '/api/threads/export'
    | '/api/training/retrain-thumbnail'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/billing'
    | '/blog'
    | '/blueprint'
    | '/clear'
    | '/cookies'
    | '/destroy'
    | '/faq'
    | '/history'
    | '/login'
    | '/niche-ranker'
    | '/partner-program'
    | '/pre-analysis'
    | '/privacy-policy'
    | '/retrain-thumbnail'
    | '/select-plan'
    | '/shadowban-detector'
    | '/support'
    | '/terms'
    | '/threads-queue'
    | '/thumbnail-test'
    | '/admin/dashboard'
    | '/admin/payouts'
    | '/api/commissions'
    | '/auth/callback'
    | '/blog/niche-finding-guide'
    | '/blog/thumbnails-matter'
    | '/partner/dashboard'
    | '/payment/success'
    | '/ref/$slug'
    | '/api/lemon/checkout'
    | '/api/lemon/portal'
    | '/api/threads/auth'
    | '/api/threads/export'
    | '/api/training/retrain-thumbnail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BillingRoute: typeof BillingRoute
  BlogRoute: typeof BlogRouteWithChildren
  BlueprintRoute: typeof BlueprintRoute
  ClearRoute: typeof ClearRoute
  CookiesRoute: typeof CookiesRoute
  DestroyRoute: typeof DestroyRoute
  FaqRoute: typeof FaqRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  NicheRankerRoute: typeof NicheRankerRoute
  PartnerProgramRoute: typeof PartnerProgramRoute
  PreAnalysisRoute: typeof PreAnalysisRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RetrainThumbnailRoute: typeof RetrainThumbnailRoute
  SelectPlanRoute: typeof SelectPlanRoute
  ShadowbanDetectorRoute: typeof ShadowbanDetectorRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ThreadsQueueRoute: typeof ThreadsQueueRoute
  ThumbnailTestRoute: typeof ThumbnailTestRoute
  ApiCommissionsRoute: typeof ApiCommissionsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PartnerDashboardRoute: typeof PartnerDashboardRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  RefSlugRoute: typeof RefSlugRoute
  ApiLemonCheckoutRoute: typeof ApiLemonCheckoutRoute
  ApiLemonPortalRoute: typeof ApiLemonPortalRoute
  ApiThreadsAuthRoute: typeof ApiThreadsAuthRoute
  ApiThreadsExportRoute: typeof ApiThreadsExportRoute
  ApiTrainingRetrainThumbnailRoute: typeof ApiTrainingRetrainThumbnailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thumbnail-test': {
      id: '/thumbnail-test'
      path: '/thumbnail-test'
      fullPath: '/thumbnail-test'
      preLoaderRoute: typeof ThumbnailTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads-queue': {
      id: '/threads-queue'
      path: '/threads-queue'
      fullPath: '/threads-queue'
      preLoaderRoute: typeof ThreadsQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadowban-detector': {
      id: '/shadowban-detector'
      path: '/shadowban-detector'
      fullPath: '/shadowban-detector'
      preLoaderRoute: typeof ShadowbanDetectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-plan': {
      id: '/select-plan'
      path: '/select-plan'
      fullPath: '/select-plan'
      preLoaderRoute: typeof SelectPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrain-thumbnail': {
      id: '/retrain-thumbnail'
      path: '/retrain-thumbnail'
      fullPath: '/retrain-thumbnail'
      preLoaderRoute: typeof RetrainThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-analysis': {
      id: '/pre-analysis'
      path: '/pre-analysis'
      fullPath: '/pre-analysis'
      preLoaderRoute: typeof PreAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-program': {
      id: '/partner-program'
      path: '/partner-program'
      fullPath: '/partner-program'
      preLoaderRoute: typeof PartnerProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niche-ranker': {
      id: '/niche-ranker'
      path: '/niche-ranker'
      fullPath: '/niche-ranker'
      preLoaderRoute: typeof NicheRankerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destroy': {
      id: '/destroy'
      path: '/destroy'
      fullPath: '/destroy'
      preLoaderRoute: typeof DestroyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clear': {
      id: '/clear'
      path: '/clear'
      fullPath: '/clear'
      preLoaderRoute: typeof ClearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint': {
      id: '/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof BlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ref/$slug': {
      id: '/ref/$slug'
      path: '/ref/$slug'
      fullPath: '/ref/$slug'
      preLoaderRoute: typeof RefSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/dashboard': {
      id: '/partner/dashboard'
      path: '/partner/dashboard'
      fullPath: '/partner/dashboard'
      preLoaderRoute: typeof PartnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/thumbnails-matter': {
      id: '/blog/thumbnails-matter'
      path: '/thumbnails-matter'
      fullPath: '/blog/thumbnails-matter'
      preLoaderRoute: typeof BlogThumbnailsMatterRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/niche-finding-guide': {
      id: '/blog/niche-finding-guide'
      path: '/niche-finding-guide'
      fullPath: '/blog/niche-finding-guide'
      preLoaderRoute: typeof BlogNicheFindingGuideRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commissions': {
      id: '/api/commissions'
      path: '/api/commissions'
      fullPath: '/api/commissions'
      preLoaderRoute: typeof ApiCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/training/retrain-thumbnail': {
      id: '/api/training/retrain-thumbnail'
      path: '/api/training/retrain-thumbnail'
      fullPath: '/api/training/retrain-thumbnail'
      preLoaderRoute: typeof ApiTrainingRetrainThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/threads/export': {
      id: '/api/threads/export'
      path: '/api/threads/export'
      fullPath: '/api/threads/export'
      preLoaderRoute: typeof ApiThreadsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/threads/auth': {
      id: '/api/threads/auth'
      path: '/api/threads/auth'
      fullPath: '/api/threads/auth'
      preLoaderRoute: typeof ApiThreadsAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lemon/portal': {
      id: '/api/lemon/portal'
      path: '/api/lemon/portal'
      fullPath: '/api/lemon/portal'
      preLoaderRoute: typeof ApiLemonPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lemon/checkout': {
      id: '/api/lemon/checkout'
      path: '/api/lemon/checkout'
      fullPath: '/api/lemon/checkout'
      preLoaderRoute: typeof ApiLemonCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogNicheFindingGuideRoute: typeof BlogNicheFindingGuideRoute
  BlogThumbnailsMatterRoute: typeof BlogThumbnailsMatterRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogNicheFindingGuideRoute: BlogNicheFindingGuideRoute,
  BlogThumbnailsMatterRoute: BlogThumbnailsMatterRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BillingRoute: BillingRoute,
  BlogRoute: BlogRouteWithChildren,
  BlueprintRoute: BlueprintRoute,
  ClearRoute: ClearRoute,
  CookiesRoute: CookiesRoute,
  DestroyRoute: DestroyRoute,
  FaqRoute: FaqRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  NicheRankerRoute: NicheRankerRoute,
  PartnerProgramRoute: PartnerProgramRoute,
  PreAnalysisRoute: PreAnalysisRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RetrainThumbnailRoute: RetrainThumbnailRoute,
  SelectPlanRoute: SelectPlanRoute,
  ShadowbanDetectorRoute: ShadowbanDetectorRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ThreadsQueueRoute: ThreadsQueueRoute,
  ThumbnailTestRoute: ThumbnailTestRoute,
  ApiCommissionsRoute: ApiCommissionsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PartnerDashboardRoute: PartnerDashboardRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  RefSlugRoute: RefSlugRoute,
  ApiLemonCheckoutRoute: ApiLemonCheckoutRoute,
  ApiLemonPortalRoute: ApiLemonPortalRoute,
  ApiThreadsAuthRoute: ApiThreadsAuthRoute,
  ApiThreadsExportRoute: ApiThreadsExportRoute,
  ApiTrainingRetrainThumbnailRoute: ApiTrainingRetrainThumbnailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
